install.packages("ggplot2")
library(ggplot2)
mpg<-as.data.frame(ggplot2::mpg)
mpg[c(65, 124, 131, 153, 212), "hwy"]<-NA
table(is.na(mpg))
is.na(mpg)
table(is.na(drv, hwy))
table(is.na(mpg$drv, mpg$hwy))
table(is.na(mpg$drv))
table(is.na(mpg$hwy))
install.packages("dplyr")
library(dplyr)
mpg_nomiss <- mpg %>% filter(!is.na(drv) & !is.na(hwy))
mean(mpg_nomiss$hwy)
table(mean(mpg_nomiss$hwy))
mpg_nomiss %>%  summarise(4 = mean(drv$))
